---

name: fivek
description: Personal Atomic Image

base-image: ghcr.io/blue-build/base-images/fedora-kinoite-nvidia-open
image-version: latest

modules:

  - type: bling
    install:
        - rpmfusion
      
  - type: os-release
    properties:
      ID: fivek
      NAME: 5k
      PRETTY_NAME: 5K
  
  - type: files
    files:
      - source: system
        destination: / 

  - type: dnf
    repos:
      copr:
        - imput/helium
    install:
      packages:
        - install-weak-deps: false
          packages:
            - helium-bin
            - https://vencord.dev/download/vesktop/amd64/rpm
    remove:
      packages:
        - firefox
        - firefox-langpacks 
        - khelpcenter

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install: 
          - org.vinegarhq.Sober
      - scope: user 

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
