---

name: fivek
description: Personal Atomic Image

base-image: ghcr.io/blue-build/base-images/fedora-kinoite-nvidia-open
image-version: latest

modules:
  - type: os-release
    properties:
      ID: fivek
      NAME: 5k
      PRETTY_NAME: 5K
  
  - type: files
    files:
      - source: system
        destination: / 

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
    remove:
      packages:
        - firefox
        - firefox-langpacks 

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install: 
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user 

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
