name: fivek
description: uBlue-based custom OS for personal use.
version: 0.1.0

base-image: ghcr.io/blue-build/base-images/fedora-silverblue-nvidia-open
image-version: latest

modules:
  
  - type: os-release
    properties:
      NAME: 5K
      PRETTY_NAME: 5K
      HOME_URL: https://github.com/Gasterboi2012/5K
      DEFAULT_HOSTNAME: 5k

  - type: script
    scripts:
      - remove-default-bg.sh

  - type: gnome-extensions
    install:
      - 517
      - 3193
      
  - type: brew
    brew-analytics: false
    auto-update: false
    auto-upgrade: false
    nofile-limits: false

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: user
        install:
          - com.mattjakeman.ExtensionManager
          - io.bassi.Amberol
          - io.missioncenter.MissionCenter
          - org.vinegarhq.Sober
          - page.tesk.Refine

  - from-file: system-packages.yml

  - type: files
    files:
      - source: system
        destination: /

  - type: initramfs

  - type: signing
